name: Renovate

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@v34
        with:
          configFile: 'renovate.json'
